# Generated by Django 3.0.8 on 2020-07-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200724_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.CharField(default='NAN', max_length=300),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='NAN', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
